# http-route.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: adminBoilerplate
  namespace: "erikmekiassen"
spec:
  parentRefs:
    - name: gke-gateway
      namespace: gateway
  hostnames:
    - admin-boilerplate-erikmekiassen.s9n.no
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: adminBoilerplate
          port: 80
