# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "erikmekiassen"

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
  - name: whoami-config
    namespace: "erikmekiassen"
    literals:
      - WHOAMI_PORT_NUMBER=8080
