# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adminBoilerplate
  namespace: "erikmekiassen"
spec:
  type: ClusterIP
  selector:
    app: adminBoilerplate
  ports:
    - name: web
      port: 80
      targetPort: http
